name: Test HTML Workflow

on:
  push:
    branches: [ main ]  # 또는 master

jobs:
  test-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Show HTML file
      run: |
        echo "== test.html 내용 =="
        cat test.html