name: Test SSH Connection to EC2

on:
  workflow_dispatch:

jobs:
  ssh-test:
    name: SSH Test (manual key setup)
    runs-on: ubuntu-latest

    steps:
    - name: Write private key to file
      run: |
        echo "${{ secrets.BJ_KIM_S }}" > id_rsa
        chmod 600 id_rsa

    - name: Test raw SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo '연결 성공'; whoami; uname -a"